apiVersion: v2
name: ankra-agent
description: Kubernetes agent for seamless cluster integration, monitoring, and automation with the Ankra platform
type: application
version: 1.0.232
appVersion: 1.0.232

keywords:
  - kubernetes
  - agent
  - monitoring
  - automation
  - management
  - cloud-native
  - devops
  - observability
  - cluster-management
  - scheduler
  - integration

home: https://ankra.io
sources:
  - https://github.com/ankraio/ankra-agent-chart

maintainers:
  - name: Ankra Team
    email: hello@ankra.io
    url: https://ankra.io

icon: https://raw.githubusercontent.com/ankraio/ankra-agent-chart/refs/heads/main/.github/logo.jpeg

annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/displayName: Ankra Agent
  artifacthub.io/alternativeName: Ankra Kubernetes Agent
