apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ankra-agent-{{ .Release.Namespace }}
  labels:
    {{- include "ankra-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ankra-agent.service_accountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: ankra-agent-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
