{{- if and .Values.config.token (not .Values.config.existing_secret_name) }}
apiVersion: v1
kind: Secret
metadata:
  name: ankra-identity-secret
type: Opaque
data:
  TOKEN: {{ .Values.config.token | b64enc }}
{{- end }}
