apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ankra-agent.service_accountName" . }}
  labels:
    {{- include "ankra-agent.labels" . | nindent 4 }}
  {{- with .Values.service_account.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
